services:
  # Native ARM64 Guacamole Client Web Application running on Tomcat 9
  guacamole:
    image: tomcat:9-jre11-slim
    container_name: guacamole-client
    restart: unless-stopped
    network_mode: host
    environment:
      GUACAMOLE_HOME: /etc/guacamole
    volumes:
      - ./webapps/guacamole.war:/usr/local/tomcat/webapps/guacamole.war:ro
      - ./config/index.jsp:/usr/local/tomcat/webapps/ROOT/index.jsp:ro
      - ./config/server.xml:/usr/local/tomcat/conf/server.xml:ro
      - ./config/guacamole.properties:/etc/guacamole/guacamole.properties:ro
      - ./config/user-mapping.xml:/etc/guacamole/user-mapping.xml:ro
